version: '2'
services:
    trident:
        # build: .
        image: tridentsdk/trident
        ports:
         - 25565:25565
        volumes:
         - /opt/tridentsdk:./server
        environment:
         - MIN_MEMORY=1G
         - MAX_MEMORY=1G